
version: '3'
services:
  smartimport:
    build: .
    ports:
      - "8080:8080"
    
#nginx:
#  restart: always
#  image: nginx:1.14-alpine
#  ports:
#    - 80:80
#  env_file:
#    - docker.env
#  depends_on:
#    - smartimport
#  volumes:
#    - nginx.conf:/etc/nginx/conf.d/default.conf
#    - logs:/logs/
#  command: >
#    nginx -g 'daemon off;'

volumes:
   logs: